services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "9000:27017"
    volumes:
      - chatWave_db:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      MONGO_URI: mongodb://mongodb:27017/chatwave
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - chatwave_node_modules:/app/node_modules
    command: "npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - chatwave_node_modules_frontend:/app/node_modules
    command: "npm run dev"

volumes:
  chatWave_db:  
  chatwave_node_modules:
  chatwave_node_modules_frontend:
